### PR TITLE
Here's what you should do.

### PR DESCRIPTION
**Pull request by ghost**
It's hard to admit when you're wrong. So I have take the liberty of writing a proper apology for you.

### CODE REVIEW

**Comment by Fuyukai** [comment]
Thanks, but it's not up to you to decide what's right or wrong. If I've violated any of Github's terms of service, I'm sure they'll let me know. But until then, I will politely reject your totalitarian imposition of false morals and keep the project up.

Best wishes. And remember, if you don't like a thing, you don't have to support it.

**Comment by ghost** [comment]
```
it's not up to you to decide what's right or wrong
```

What's right and wrong is decided by a society and a culture and enforced both by laws and public critique.

```
totalitarian imposition of false morals
```

It's just a pull request dude. So I'm not really imposing anything am I? I just thought I'd make it easy for you to admit your mistake and apologize.

```
if you don't like a thing, you don't have to support it.
```

Please remember, that if I don't like a thing, I can not only not support it but also tell you I don't like it and tell everyone I know that they should tell you they don't like it. That's the great thing about free speach, am I right?!

**Comment by Fuyukai** [comment]
If you search Twitter, the people who enjoy this seem to far outnumber the few who choose to call it offensive. And among those who enjoy it are several women. So really, I think you would do well to remember that your opinion is only that -- an opinion. It is not a fact, and you do not speak for everyone.

Please feel free to dislike my sense of humor. And feel free to tell all your friends to come here and check out how terrible my project is... As you may have figured out by now, I enjoy the attention. You're only helping DICSS to become the most popular Javascript project on Github today, so by all means keep it up.

The best way to make things go away is to ignore them. Maybe instead of wasting your time and attention on fighting with one silly guy on the internet, you could be using all that vim and vigor to create a project that is more interesting, more useful, more popular, or even just more funny than mine.

**Comment by ghost** [comment]
```
among those who enjoy it are several women
```

Several?! Wow. My mistake, then. As long as a few women found it funny, who gives a shit what the others thought.

```
I enjoy the attention.
```

I get it. You're a bro. You're a troll. You think that it's fun to ruffle feathers. You don't care if you hurt people as long as you get your lulz.

```
The best way to make things go away is to ignore them.
```

Of course, all this attention means people will keep using this amazing technology for years to come.

```
you do not speak for everyone.
```

Actually, there was a straw pull and I drew the short straw and had to be the one who to tell you your business.

**Pull request closed without merging**
